import { Outfit } from 'next/font/google';
import "./globals.css";
import NavBar from '@/components/NavBar/NavBar';
import Footer from '@/components/Footer/Footer';

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={outfit.className}>
    <NavBar/>
    {children}
    <Footer/>

      </body>
    </html>
  );
}
